package com.me.injin.testcodewitharchitecturekotlin.mock

import com.me.injin.testcodewitharchitecturekotlin.post.domain.Post
import com.me.injin.testcodewitharchitecturekotlin.post.service.port.PostRepository

class FakePostRepository() : PostRepository {

    private val autoGeneratedId: Long = 0L
    private val data = mutableListOf<Post>()
    override fun findById(id: Long): Post? {
        return data.find { it.id == id }
    }

    override fun save(post: Post): Post {
        if (post.id == null || post.id == 0L) {
            val newPost = post.copy(id = autoGeneratedId + 1)
            data.add(newPost)
            return newPost
        } else {
            data.removeIf { it.id == post.id }
            data.add(post)
            return post
        }
    }
}
